/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CombinacoesIndexRouteImport } from './routes/combinacoes.index'
import { Route as CombinacoesSlugRouteImport } from './routes/combinacoes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CombinacoesIndexRoute = CombinacoesIndexRouteImport.update({
  id: '/combinacoes/',
  path: '/combinacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CombinacoesSlugRoute = CombinacoesSlugRouteImport.update({
  id: '/combinacoes/$slug',
  path: '/combinacoes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/combinacoes/$slug': typeof CombinacoesSlugRoute
  '/combinacoes/': typeof CombinacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combinacoes/$slug': typeof CombinacoesSlugRoute
  '/combinacoes': typeof CombinacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/combinacoes/$slug': typeof CombinacoesSlugRoute
  '/combinacoes/': typeof CombinacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/combinacoes/$slug' | '/combinacoes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/combinacoes/$slug' | '/combinacoes'
  id: '__root__' | '/' | '/combinacoes/$slug' | '/combinacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CombinacoesSlugRoute: typeof CombinacoesSlugRoute
  CombinacoesIndexRoute: typeof CombinacoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combinacoes/': {
      id: '/combinacoes/'
      path: '/combinacoes'
      fullPath: '/combinacoes/'
      preLoaderRoute: typeof CombinacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combinacoes/$slug': {
      id: '/combinacoes/$slug'
      path: '/combinacoes/$slug'
      fullPath: '/combinacoes/$slug'
      preLoaderRoute: typeof CombinacoesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CombinacoesSlugRoute: CombinacoesSlugRoute,
  CombinacoesIndexRoute: CombinacoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
